In [2]:
import numpy as np


In [4]:
x = np.array([1,2,3])

In [5]:
x

array([1, 2, 3])

In [6]:
y=np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
z= np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [9]:
z

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])