In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib

Using matplotlib backend: <object object at 0x000001E4AEE9EFA0>


In [34]:
from sklearn.datasets import load_boston

In [35]:
boston=load_boston()

C:\Users\NV_User\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset

In [36]:
x=boston.data
y=boston.target

In [37]:
dir(boston)

['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'target']

In [38]:
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [39]:
from sklearn.linear_model import Ridge

In [67]:
r=Ridge(fit_intercept=False)

In [68]:
r.fit(x,y)

Ridge(fit_intercept=False)

In [69]:
r.intercept_

0.0

In [70]:
results=pd.DataFrame(list(zip(boston.feature_names,r.coef_)),columns=['variable','coef'])

In [71]:
results

variable      coef
0      CRIM -0.092711
1        ZN  0.049055
2     INDUS -0.008746
3      CHAS  2.755020
4       NOX -1.872889
5        RM  5.868193
6       AGE -0.007879
7       DIS -0.959196
8       RAD  0.171845
9       TAX -0.009604
10  PTRATIO -0.389557
11        B  0.014877
12    LSTAT -0.422148

In [72]:
from sklearn.linear_model import LinearRegression

In [73]:
reg=LinearRegression()

In [74]:
reg

LinearRegression()

In [75]:
reg.fit(x,y)

LinearRegression()

In [76]:
reg.coef_

array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
       -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
        3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
       -5.24758378e-01])

In [77]:
reg.intercept_

36.459488385089855

In [78]:
plt.plot(r.coef_)
plt.plot(reg.coef_ ,c='red')
plt.show()

In [79]:
print(np.min(r.coef_),np.min(reg.coef_))

-1.872889070341414 -17.766611228299986


In [80]:
alphaSpace=np.logspace(-5,5,20)
ridge_coefs=[]

In [84]:
for alpha in alphaSpace:
    r=Ridge(alpha=alpha,fit_intercept=False)
    r.fit(x,y)
    ridge_coefs.append(r.coef_)
    

In [85]:
ridge_coefs

[array([-9.28965139e-02,  4.87149591e-02, -4.06005053e-03,  2.85399773e+00,
        -2.86842187e+00,  5.92814697e+00, -7.26934551e-03, -9.68514034e-01,
         1.71151137e-01, -9.39621834e-03, -3.92190899e-01,  1.49056096e-02,
        -4.16304549e-01]),
 array([-9.28965064e-02,  4.87149685e-02, -4.06021795e-03,  2.85399515e+00,
        -2.86838764e+00,  5.92814506e+00, -7.26937131e-03, -9.68513744e-01,
         1.71151157e-01, -9.39622530e-03, -3.92190836e-01,  1.49056080e-02,
        -4.16304735e-01]),
 array([-9.28964813e-02,  4.87149999e-02, -4.06078046e-03,  2.85398649e+00,
        -2.86827266e+00,  5.92813865e+00, -7.26945799e-03, -9.68512768e-01,
         1.71151226e-01, -9.39624866e-03, -3.92190624e-01,  1.49056028e-02,
        -4.16305358e-01]),
 array([-9.28963970e-02,  4.87151054e-02, -4.06267004e-03,  2.85395739e+00,
        -2.86788640e+00,  5.92811712e+00, -7.26974915e-03, -9.68509491e-01,
         1.71151456e-01, -9.39632713e-03, -3.92189910e-01,  1.49055853e-02,
       

In [86]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import cross_val_score

In [87]:
x=load_boston().data
y=load_boston().target

C:\Users\NV_User\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset

In [88]:
alpha_space=np.logspace(-5,5,50)
ridge_score=[]
ridge_score_std=[]

ridge=Ridge(fit_intercept=False)


In [89]:
for alpha in alpha_space:
    ridge.alpha=alpha
    
    ridge_cv_score=cross_val_score(ridge,x,y,cv=10)
    
    ridge_score.append(np.mean(ridge_cv_score))
    ridge_score_std.append(np.std(ridge_cv_score))

In [92]:
# from sklearn.metrics import mean_squared_error, make_scorer

In [93]:
# mse=make_scorer(mean_squared_error)


In [95]:
from sklearn.model_selection import GridSearchCV

In [96]:
?GridSearchCV

In [97]:
alpha_Space=np.logspace(-5,5,25)
param_grid={'alpha':alpha_Space}

In [98]:
Gred_cv=GridSearchCV(ridge,param_grid=param_grid,cv=5)

In [99]:
Gred_cv.fit(x,y)

GridSearchCV(cv=5, estimator=Ridge(alpha=100000.0, fit_intercept=False),
             param_grid={'alpha': array([1.00000000e-05, 2.61015722e-05, 6.81292069e-05, 1.77827941e-04,
       4.64158883e-04, 1.21152766e-03, 3.16227766e-03, 8.25404185e-03,
       2.15443469e-02, 5.62341325e-02, 1.46779927e-01, 3.83118685e-01,
       1.00000000e+00, 2.61015722e+00, 6.81292069e+00, 1.77827941e+01,
       4.64158883e+01, 1.21152766e+02, 3.16227766e+02, 8.25404185e+02,
       2.15443469e+03, 5.62341325e+03, 1.46779927e+04, 3.83118685e+04,
       1.00000000e+05])})

In [100]:
Gred_cv.best_params_

{'alpha': 17.78279410038923}

In [101]:
Gred_cv.best_score_

0.43752718982971484