In [1]:
import pandas as pd
import numpy as np
import matplotlip as plt
import seaborn as sns 
%matplotlib inline

In [2]:
 from  sklearn.datasets import load_boston

In [3]:
x=load_boston().data
y=load_boston().target

C:\Users\NV_User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        

In [4]:
boston=pd.DataFrame(x , columns=load_boston().feature_names)

In [5]:
boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [6]:
from sklearn.model_selection import KFold

In [7]:
kf=KFold(n_splits=5 ,shuffle=True ,random_state=10123)

In [8]:
type(kf)

sklearn.model_selection._split.KFold

In [9]:
splits=kf.split(x)

In [12]:
for train_index ,val_index in splits:
    print("num of tarning index{:s}".format(len (train_index)))
    print("num of validation index{:s}".format(len (val_index)))

In [13]:
x=np.arange(1,51)
y=np.array([np.repeat(1,25),np.repeat(2,25)]).flatten()

In [14]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [15]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2])

In [16]:
from sklearn.model_selection import KFold

In [51]:
kf_=KFold(n_splits=5,shuffle=True,random_state=10123) #random عشان العشوائية كل مره تطلع نفس الناتج
splits=kf_.split(x)

In [52]:
for train_index ,val_index in splits:
    print(len (train_index),len (val_index))
   

40 10
40 10
40 10
40 10
40 10


In [53]:
print(train_index ,val_index)

[ 0  1  2  3  5  6  7  8  9 10 12 16 17 18 19 21 22 23 24 25 26 27 31 32
 33 34 35 36 37 38 39 40 42 43 44 45 46 47 48 49] [ 4 11 13 14 15 20 28 29 30 41]


In [85]:
x=load_boston().data
y=load_boston().target

C:\Users\NV_User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        

In [86]:
kf=KFold(n_splits=5 ,shuffle=True ,random_state=10123)

In [87]:
splits=kf.split(x)

In [88]:
for train_index ,val_index in splits:
    print("num of tarning index{:8}".format(len (train_index)))
    print("num of validation index{:8}".format(len (val_index)))

num of tarning index     404
num of validation index     102
num of tarning index     405
num of validation index     101
num of tarning index     405
num of validation index     101
num of tarning index     405
num of validation index     101
num of tarning index     405
num of validation index     101


In [89]:
for train_index ,val_index in splits:
    print(train_index,val_index)

In [90]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error ,mean_absolute_error

In [91]:
lreg =LinearRegression()

In [101]:
kf=KFold(n_splits=5 ,shuffle=True ,random_state=10123)
splits=kf.split(x)

In [102]:
for train_index ,val_index in splits:
    x_train,y_train =x[train_index],y[train_index]
    x_val ,y_val=x[val_index],y[val_index]
    
    lreg.fit( x_train,y_train)
    
    preds=lreg.predict( x_val)
    print("the mse metric: {:.5f}".format(mean_squared_error(y_val,preds)))
    print("the mae metric: {:.5f}".format(mean_absolute_error(y_val,preds)))
    print()

the mse metric: 19.99443
the mae metric: 3.37722

the mse metric: 39.91115
the mae metric: 3.74241

the mse metric: 22.85837
the mae metric: 3.30429

the mse metric: 21.65831
the mae metric: 3.58502

the mse metric: 18.20975
the mae metric: 3.03346



In [103]:
x=load_boston().data
y=load_boston().target

C:\Users\NV_User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        

In [104]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

In [105]:
lreg=LinearRegression()

In [112]:
cv_results=cross_val_score(lreg,x,y,cv=5) #دي بتحسب ال r square

In [113]:
print(type(cv_results))

<class 'numpy.ndarray'>


In [114]:
cv_results

array([ 0.63919994,  0.71386698,  0.58702344,  0.07923081, -0.25294154])

In [116]:
avg_r_sq=np.mean(cv_results) #ال average
print(f"the average R^2 is:{avg_r_sq:.4f}" )

the average R^2 is:0.3533


In [119]:
from sklearn.metrics import make_scorer ,mean_absolute_error
mae= make_scorer(mean_absolute_error)
cross_val_score(lreg,x,y,cv=5 , scoring=mae)

array([2.62190565, 3.90725478, 4.386606  , 5.57073637, 4.76333993])